spring:
  application:
    name: mymail-api
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/mymail
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



auth0:
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_API_IDENTIFIER}


